# SOURCE to update change: tmux source ~/Github/scripts/.tmux.conf

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set-window-option -g pane-base-index 1

# Allow mouse usage
set -g mouse on

# Let applications inside tmux send OSC sequences (incl. OSC 52 clipboard) to the terminal
set -g allow-passthrough on

# Enable tmux clipboard integration (OSC 52)
set -g set-clipboard on

# Reload via PREFIX+r
unbind r
bind r source-file ~/Github/scripts/.tmux.conf \; display "Reloaded ~/Github/scripts/.tmux.conf"